name: CI
on: [push]

jobs:
    documentation:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: pip install pydocstyle
            - run: pydocstyle --convention numpy
    formatting:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: pip install flake8
            - run: flake8 --show-source
    install:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: conda-incubator/setup-miniconda@v2
              with:
                  environment-file: environment.yml
            - run: |
                  conda info
                  conda list
            - run: python train.py --iters 1 --no_eval
