name: CI
on: [push]

jobs:
    documentation:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: pip install pydocstyle
            - run: pydocstyle
    formatting:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: pip install flake8
            - run: flake8
    installation:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: ls -a
            - uses: conda-incubator/setup-miniconda@v2
              with:
                  activate-environment: trajectory
                  environment-file: environment.yml
            - shell: bash -l {0}
              run: |
                  conda info
                  conda list
                  conda env list
                  which python
            - shell: bash -l {0}
              run: python train.py --iters 1 --no_eval
