name: CI
on: [push]

jobs:
    formatting:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: pip install pydocstyle
            - run: pydocstyle --convention numpy
            - run: pip install flake8
            - run: flake8 --show-source
